package com.hea3ven.tools.asmtweaks.editors.opcodes;

import org.objectweb.asm.Opcodes;

public enum InsnOpcodes {
	NOP(Opcodes.NOP),
	ACONST_NULL(Opcodes.ACONST_NULL),
	ICONST_M1(Opcodes.ICONST_M1),
	ICONST_0(Opcodes.ICONST_0),
	ICONST_1(Opcodes.ICONST_1),
	ICONST_2(Opcodes.ICONST_2),
	ICONST_3(Opcodes.ICONST_3),
	ICONST_4(Opcodes.ICONST_4),
	ICONST_5(Opcodes.ICONST_5),
	LCONST_0(Opcodes.LCONST_0),
	LCONST_1(Opcodes.LCONST_1),
	FCONST_0(Opcodes.FCONST_0),
	FCONST_1(Opcodes.FCONST_1),
	FCONST_2(Opcodes.FCONST_2),
	DCONST_0(Opcodes.DCONST_0),
	DCONST_1(Opcodes.DCONST_1),
	IALOAD(Opcodes.IALOAD),
	LALOAD(Opcodes.LALOAD),
	FALOAD(Opcodes.FALOAD),
	DALOAD(Opcodes.DALOAD),
	AALOAD(Opcodes.AALOAD),
	BALOAD(Opcodes.BALOAD),
	CALOAD(Opcodes.CALOAD),
	SALOAD(Opcodes.SALOAD),
	IASTORE(Opcodes.IASTORE),
	LASTORE(Opcodes.LASTORE),
	FASTORE(Opcodes.FASTORE),
	DASTORE(Opcodes.DASTORE),
	AASTORE(Opcodes.AASTORE),
	BASTORE(Opcodes.BASTORE),
	CASTORE(Opcodes.CASTORE),
	SASTORE(Opcodes.SASTORE),
	POP(Opcodes.POP),
	POP2(Opcodes.POP2),
	DUP(Opcodes.DUP),
	DUP_X1(Opcodes.DUP_X1),
	DUP_X2(Opcodes.DUP_X2),
	DUP2(Opcodes.DUP2),
	DUP2_X1(Opcodes.DUP2_X1),
	DUP2_X2(Opcodes.DUP2_X2),
	SWAP(Opcodes.SWAP),
	IADD(Opcodes.IADD),
	LADD(Opcodes.LADD),
	FADD(Opcodes.FADD),
	DADD(Opcodes.DADD),
	ISUB(Opcodes.ISUB),
	LSUB(Opcodes.LSUB),
	FSUB(Opcodes.FSUB),
	DSUB(Opcodes.DSUB),
	IMUL(Opcodes.IMUL),
	LMUL(Opcodes.LMUL),
	FMUL(Opcodes.FMUL),
	DMUL(Opcodes.DMUL),
	IDIV(Opcodes.IDIV),
	LDIV(Opcodes.LDIV),
	FDIV(Opcodes.FDIV),
	DDIV(Opcodes.DDIV),
	IREM(Opcodes.IREM),
	LREM(Opcodes.LREM),
	FREM(Opcodes.FREM),
	DREM(Opcodes.DREM),
	INEG(Opcodes.INEG),
	LNEG(Opcodes.LNEG),
	FNEG(Opcodes.FNEG),
	DNEG(Opcodes.DNEG),
	ISHL(Opcodes.ISHL),
	LSHL(Opcodes.LSHL),
	ISHR(Opcodes.ISHR),
	LSHR(Opcodes.LSHR),
	IUSHR(Opcodes.IUSHR),
	LUSHR(Opcodes.LUSHR),
	IAND(Opcodes.IAND),
	LAND(Opcodes.LAND),
	IOR(Opcodes.IOR),
	LOR(Opcodes.LOR),
	IXOR(Opcodes.IXOR),
	LXOR(Opcodes.LXOR),
	I2L(Opcodes.I2L),
	I2F(Opcodes.I2F),
	I2D(Opcodes.I2D),
	L2I(Opcodes.L2I),
	L2F(Opcodes.L2F),
	L2D(Opcodes.L2D),
	F2I(Opcodes.F2I),
	F2L(Opcodes.F2L),
	F2D(Opcodes.F2D),
	D2I(Opcodes.D2I),
	D2L(Opcodes.D2L),
	D2F(Opcodes.D2F),
	I2B(Opcodes.I2B),
	I2C(Opcodes.I2C),
	I2S(Opcodes.I2S),
	LCMP(Opcodes.LCMP),
	FCMPL(Opcodes.FCMPL),
	FCMPG(Opcodes.FCMPG),
	DCMPL(Opcodes.DCMPL),
	DCMPG(Opcodes.DCMPG),
	IRETURN(Opcodes.IRETURN),
	LRETURN(Opcodes.LRETURN),
	FRETURN(Opcodes.FRETURN),
	DRETURN(Opcodes.DRETURN),
	ARETURN(Opcodes.ARETURN),
	RETURN(Opcodes.RETURN),
	ARRAYLENGTH(Opcodes.ARRAYLENGTH),
	ATHROW(Opcodes.ATHROW),
	MONITORENTER(Opcodes.MONITORENTER),
	MONITOREXIT(Opcodes.MONITOREXIT);

	private final int opcode;

	InsnOpcodes(int opcode) {
		this.opcode = opcode;
	}

	public int getOpcode() {
		return opcode;
	}
}
